[gcp_service_account]
type = "service_account"
project_id = "storied-imprint-482607-f2"
private_key_id = "c634fc12d93d8e1b16f0ff11b29945bbcb1bf14e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKkwggSkAgEAAoIBAQCo1+3JSB5dtea8
GYv8BsnzIIAUqZSBPBe/JsqwCrbCKjFZPYolnLz60+BjD+hqrsJUmu66VmVGnXwL
FqJ1YJz5dzGefgXr+EKwFOZk3NPIsBX536XvJxn0JIeKAmKT9SNOhLWdsV9qdwia
SdqLqlvwdepx5In1Ygl/0FzEcf5niGfAtUFzVIQ4pARFmAc9tfN7Q/rzn0ki6QW1
V488j9k1XZimseRUxYpWc4CI+oujkHPzRDYPxQE4PIojlAAxqKZ4nXV3z1QVn9f8
PA1azMZxcfA72zNDF0BO2BlWbYGcAJppCvkyjo/v4GxdtZJuJ0lsi4y4/o3m0V3f
zYXbpCFTAgMBAAECggEAJ7yp+fU/ME7fPuXETExMuyuq+THwAXpjHFnE2imrWYcU
liwllzSMRXwYEzhrOrBmjALqrHAo5bWqu/FXysgyKYQj6Wk/e4myKD7C+nn+Xf0T
Lvuz0dUiBpOSUqi9CpVm+dPB6psUGbpqC+XVyYkOmkkmJCflUBsCoVIogxNRDIxr
cRu0g2Aj4jF+fyUnqFpgMagpvCka0+2mzOdoIxngr+GzaWzshlYKIx3a+Ey4EaF9
y2/7lPU9TCaiapwPc+NhmCHeWt4ryG8CyzhgcO3XdWi5cYmAwa9pNGMnms3Qziua
FnzpQnTGyliFkYpIqbl+jY4EZ+pNRvpnBO/qoHc0AQKBgQDnhhSNpmJBs1F4s9+9
qTPn5wk4cWF1REJUrnQq6JqVZuWzoKNLy+mg7SCD+KjlyNsr2r+EZ4Kvr0QNDA2n
+xX7y+nHdmgFNes2pdyt+eHtsaZRalxm5riZpR/bZ1AUiyUvErl5ms7XIIWkGhxh
REMQFz2yMKFNUqDVjIQDJ+JCewKBgQC6sXrmRbLvoJX8a/Mg/aLVNH058Gbfmobp
aoDJEQDi+wr11bgwpX85MWyDGcBhXgBx1vY8upGu/TiDLdtsIYvvy3MKeX6RJ35F
BKkBN0C/u4sbuhO9TcLaHlxstN4HsEC56IadWJQEPl7EYRP6IEunsHK75RDzR5Su
k7QB5i7xCQKBgQCfmBVi72ab03g9tABvRMu698+rULzVkRAIP5lkWqL0idGdWQY3
oYCSpeLcFfSXMTWjrU6HfrLfV/mY5M4lFTe6Mn4cOMrLjLdvHDZa1v2eU+9J//9i
D3kAsIqdO0JAZwpiwI2J/eTG9mwpCra1ddCkruCgjFUkb+jeS9ZUNpIJMQKBgQCN
nutkbYcRzCI104Rrla8gnZb6/spLWpABRyYnVmvP6XS037jTzsWBBMhU3/d+/y1Y5
FkE/Xz/kAdbaN4EBuQH8XI6MYCnG1p2UlfIbuy+Lnzv/I6eCqjsHzc7KtBBu885f
lHhFkY5lHlhha3V4CPaGanzfygmxNyFX20fnvTDbyQKBgGv2AUM2E98uTqTB6gfk
mZa2baW9TiyFPjMHk7EiDxa5lgq+Z+AiBsdnsXCQ9jEB3UhFv/w7R1d0ZlB4wsda
6KiCWDejEmQ+WlhsT7u73HMKYdLmNvQIWlTuX/S2dlesD9EJY3puL7KGIHJM/CtN
h3DgLp+RmDPYuq+PzW5VegmG
-----END PRIVATE KEY-----"""
client_email = "python-api@storied-imprint-482607-f2.iam.gserviceaccount.com"
client_id = "112876135567540366386"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/python-api%40storied-imprint-482607-f2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
